version: '3.7'

networks:
    web-utilisateurs:
        external: true

volumes:
    mysql_data:

services:
    traefik:
        image: traefik:v2.10
        container_name: traefik
        command:
            - "--api.dashboard=true"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
            - "traefik.http.routers.api.service=api@internal"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - web-utilisateurs

    db:
        image: mysql:latest
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: motdepasse
            MYSQL_DATABASE: ma_base_de_donnees
        networks:
            - web-utilisateurs
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis:latest
        container_name: redis
        networks:
            - web-utilisateurs

    utilisateurs:
        image: utilisateurs_web_image:latest
        container_name: mon-serveur-web
        volumes:
            - ./php/index.php:/var/www/html/index.php
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mon-serveur-web.rule=Host(`utilisateurs.localhost`)"
            - "traefik.http.services.mon-serveur-web.loadbalancer.server.port=80"
        networks:
            - web-utilisateurs
        depends_on:
            - db
            - redis
            - traefik

    clusterswarm:
        image: clusterswarm_web_image:latest
        deploy:
            replicas: 5
        networks:
            - web-utilisateurs
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.clusterswarm.rule=Host(`clusterswarm.localhost`)"
            - "traefik.http.services.clusterswarm.loadbalancer.server.port=80"

    web-fortune:
        image: fortune_app_image:latest
        container_name: mon-serveur-web-fortune
        volumes:
            - ./fortune/index.php:/var/www/html/index.php
            - ./fortune/images:/var/www/html/images
            - ./fortune/convert.sh:/root/convert.sh
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.fortune.rule=Host(`fortune.localhost`)"
            - "traefik.http.services.fortune.loadbalancer.server.port=80"
        networks:
            - web-utilisateurs
        depends_on:
            - traefik

    apache_web:
        build:
            context: ./services/apache
        image: apache_web_image:latest
        volumes:
            - ./services/apache/index.php:/var/www/html/index.php
        networks:
            - traefik-public
            - app-apache
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik-public"
            - "traefik.http.routers.apache.rule=PathPrefix(`/apache`)"
            - "traefik.http.routers.apache.entrypoints=web"
            - "traefik.http.routers.apache.middlewares=auth"