version: '3.7'

networks:
    web-utilisateurs:
        external: true

volumes:
    mysql_data:

services:
    traefik:
        image: traefik:v2.10
        command:
            - "--api.dashboard=true"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
            - "traefik.http.routers.api.service=api@internal"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - web-utilisateurs

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: motdepasse
            MYSQL_DATABASE: ma_base_de_donnees
        networks:
            - web-utilisateurs
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis:latest
        networks:
            - web-utilisateurs

    # Service utilisateurs
    utilisateurs:
        image: utilisateurs_web_image:latest
        deploy:
            replicas: 1
        volumes:
            - ./php/index.php:/var/www/html/index.php
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.utilisateurs.rule=Host(`utilisateurs.localhost`)"
            - "traefik.http.services.utilisateurs.loadbalancer.server.port=80"
        networks:
            - web-utilisateurs
        depends_on:
            - db
            - redis
            - traefik

    # Service clusterswarm
    clusterswarm:
        image: clusterswarm_web_image:latest
        deploy:
            replicas: 1
        networks:
            - web-utilisateurs
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.clusterswarm.rule=Host(`clusterswarm.localhost`)"
            - "traefik.http.services.clusterswarm.loadbalancer.server.port=80"
